"""
Strategy Engine – the brain of the system.

Takes brand identity + market research + product list and outputs a complete
**CampaignStrategy** containing per-product creative plans and general-brand
creative plans.

Creative decisions (visual style, pacing, layout, video style) are always
deterministic lookup tables.  Messaging text (headlines, CTAs, secondary
messages) is generated by OpenAI when ``OPENAI_API_KEY`` is set, otherwise
falls back to the same deterministic templates.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field, asdict
from typing import Dict, List, Optional

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.enums import (
    CampaignGoal,
    LayoutType,
    MessageAngle,
    Platform,
    VariantType,
    VideoStyle,
    VideoType,
    VisualStyle,
)
from app.schemas.brand import BrandIdentity, MarketResearch
from app.schemas.product import ProductInput
from app.services.strategy.decision_matrices import (
    resolve_brand_primary_message,
    resolve_cta,
    resolve_layout_type,
    resolve_message_angles,
    resolve_pacing,
    resolve_product_primary_message,
    resolve_secondary_message,
    resolve_video_style,
    resolve_visual_style,
)
from app.services.strategy.platform_specs import get_platform_spec
from app.services.strategy.template_selector import select_templates


# ── Data classes that form the strategy output ──────────────

VARIANT_TYPES = [VariantType.VARIANT_A, VariantType.VARIANT_B, VariantType.VARIANT_C]


def _dedupe_urls(urls: List[str]) -> List[str]:
    """Preserve order while removing empty/duplicate URLs."""
    seen = set()
    cleaned: List[str] = []
    for url in urls:
        if not url:
            continue
        if url in seen:
            continue
        cleaned.append(url)
        seen.add(url)
    return cleaned


def _normalize_url_list(primary: Optional[str], extras: Optional[List[str]]) -> List[str]:
    urls: List[str] = []
    if primary:
        urls.append(primary)
    if extras:
        urls.extend(extras)
    return _dedupe_urls(urls)


def _resolve_static_image_pool(prod: ProductInput) -> tuple[List[str], bool]:
    """
    Resolve the image pool for static ads.

    Returns (pool, is_override):
      - pool: list of URLs to rotate across variants
      - is_override: True when using explicit static ad hero images (image_url[s])
    """
    static_urls = _normalize_url_list(
        getattr(prod, "image_url", None),
        getattr(prod, "image_urls", None),
    )
    if static_urls:
        return static_urls, True

    product_urls = _normalize_url_list(
        getattr(prod, "product_image_url", None),
        getattr(prod, "product_image_urls", None),
    )
    return product_urls, False


@dataclass
class VideoVariantPlan:
    """Blueprint for one video file to be generated."""
    variant_id: int
    variant_type: str
    message_angle: str
    primary_message: str
    secondary_message: str
    cta_text: str
    template_id: Optional[str] = None
    pacing: str = "medium"
    pacing_seconds: float = 3.0


@dataclass
class StaticAdVariantPlan:
    """Blueprint for one static ad image to be generated."""
    variant_id: int
    variant_type: str
    message_angle: str
    headline: str
    subheading: str
    cta_text: str
    body_text: str = ""
    static_template_id: str = ""
    static_template_name: str = ""
    image_url: Optional[str] = None


@dataclass
class ProductCreativePlan:
    """Creative plan for all variants of a single product."""
    product_index: int
    product_name: str
    video_style: str
    visual_style: str
    variants: List[VideoVariantPlan] = field(default_factory=list)
    static_ad_variants: List[StaticAdVariantPlan] = field(default_factory=list)


@dataclass
class GeneralBrandPlan:
    """Creative plan for general-brand / collection videos."""
    layout_types: List[str] = field(default_factory=list)
    products_shown: List[str] = field(default_factory=list)  # product names
    visual_style: str = "soft_premium"
    variants: List[VideoVariantPlan] = field(default_factory=list)
    static_ad_variants: List[StaticAdVariantPlan] = field(default_factory=list)


@dataclass
class CampaignStrategy:
    """The complete creative strategy for an entire campaign."""
    visual_style: str
    pacing: str
    pacing_seconds: float
    message_angles: List[str]
    product_plans: List[ProductCreativePlan] = field(default_factory=list)
    brand_plan: Optional[GeneralBrandPlan] = None
    platforms: List[str] = field(default_factory=list)
    total_videos: int = 0
    total_static_ads: int = 0

    def to_dict(self) -> dict:
        return asdict(self)


# ── Main entry point ────────────────────────────────────────

async def generate_campaign_strategy(
    *,
    brand: BrandIdentity,
    market: MarketResearch,
    products: List[ProductInput],
    goal: CampaignGoal,
    platforms: List[Platform],
    duration: int,
    product_variants: int = 3,
    brand_variants: int = 3,
    db: Optional[AsyncSession] = None,
) -> CampaignStrategy:
    """
    Generate the full creative strategy.

    Visual / structural decisions → deterministic lookup tables (always).
    Messaging text → OpenAI GPT-5.1 when available, template fallback otherwise.
    """

    # 1. Global visual style from market position
    saturation_level = market.saturation_level
    visual_style = resolve_visual_style(saturation_level, market.competitive_edge_percent)
    pacing_label, pacing_secs = resolve_pacing(visual_style)

    # 2. Message angles (one per variant slot, cycling priority)
    angles = resolve_message_angles(goal, max(product_variants, brand_variants))

    # 3. Aspect ratios we need
    aspect_ratios = []
    for p in platforms:
        spec = get_platform_spec(p)
        if spec.aspect_ratio not in aspect_ratios:
            aspect_ratios.append(spec.aspect_ratio)

    # ── Generate AI copy for all products in one pass ──────
    from app.services.strategy.copywriter import generate_product_copy, generate_brand_copy

    ai_product_copies: Dict[int, list] = {}  # idx → List[ProductCopy]
    for idx, prod in enumerate(products):
        copies = await generate_product_copy(
            product_name=prod.product_name,
            product_description=prod.product_description,
            product_category=prod.product_category,
            product_tags=prod.tags,
            brand_name=brand.brand_name,
            brand_voice=brand.voice,
            brand_tone=brand.tone,
            message_angle=angles[0].value,
            campaign_goal=goal.value,
            num_variants=product_variants,
        )
        if copies is not None:
            ai_product_copies[idx] = copies

    ai_brand_copies = await generate_brand_copy(
        brand_name=brand.brand_name,
        brand_voice=brand.voice,
        brand_tone=brand.tone,
        brand_industry=brand.industry,
        product_names=[p.product_name for p in products],
        campaign_goal=goal.value,
        message_angles=[a.value for a in angles[:brand_variants]],
        num_variants=brand_variants,
    )

    # ── Select static ad templates ──────────────────────────
    from app.services.static_ad.template_selector import (
        select_static_ad_templates,
        select_brand_static_templates,
    )

    # 4. Per-product creative plans
    product_plans: List[ProductCreativePlan] = []
    for idx, prod in enumerate(products):
        video_style = resolve_video_style(prod.product_category)
        secondary_fallback = resolve_secondary_message(market.sentiment)

        # Select templates if DB session available
        template_ids: List[str] = []
        if db is not None:
            templates = await select_templates(
                db,
                visual_style=visual_style,
                video_style=video_style,
                duration=duration,
                aspect_ratios=aspect_ratios,
                industry=brand.industry,
                limit=product_variants,
            )
            template_ids = [str(t.id) for t in templates]

        variants: List[VideoVariantPlan] = []
        for vi in range(product_variants):
            angle = angles[vi % len(angles)]

            # Try AI copy first, fall back to templates
            if idx in ai_product_copies and vi < len(ai_product_copies[idx]):
                ai = ai_product_copies[idx][vi]
                primary = ai.primary_message
                secondary = ai.secondary_message
                cta = ai.cta_text
            else:
                primary = resolve_product_primary_message(prod.tags, vi)
                secondary = secondary_fallback
                cta = resolve_cta(goal, is_brand=False, variant_idx=vi)

            variants.append(VideoVariantPlan(
                variant_id=vi + 1,
                variant_type=VARIANT_TYPES[vi % len(VARIANT_TYPES)].value,
                message_angle=angle.value,
                primary_message=primary,
                secondary_message=secondary,
                cta_text=cta,
                template_id=template_ids[vi] if vi < len(template_ids) else None,
                pacing=pacing_label,
                pacing_seconds=pacing_secs,
            ))

        image_pool, image_override = _resolve_static_image_pool(prod)
        # Generate more static ad variants for better variety and multi-image support
        # Minimum 12 ads per product to showcase different templates and styles
        if image_pool:
            # For multi-image products: generate at least 3 templates per image
            static_variant_count = max(12, len(image_pool) * 3)
        else:
            # Even without extra images, generate 12+ variants with diverse templates
            static_variant_count = 12

        # Select static ad templates for this product (full context)
        static_ad_templates = select_static_ad_templates(
            goal=goal,
            message_angles=[angles[vi % len(angles)] for vi in range(static_variant_count)],
            industry=brand.industry,
            product_category=prod.product_category,
            visual_style=visual_style.value,
            has_product_image=bool(getattr(prod, "product_image_url", None) or getattr(prod, "product_image_urls", None)),
            count=static_variant_count,
            sentiment=market.sentiment.value,
            target_age_min=market.target_audience_age_min,
            target_age_max=market.target_audience_age_max,
            target_gender=market.target_audience_gender,
            price=prod.price,
            trending_keywords=market.trending_keywords,
        )

        # Generate static ad copy (AI or smart deterministic)
        from app.services.static_ad.copywriter import (
            generate_static_ad_copy_ai,
            generate_static_ad_copy_deterministic,
        )

        ai_static_copies = None
        if getattr(prod, "product_image_url", None) or getattr(prod, "product_image_urls", None):
            ai_static_copies = await generate_static_ad_copy_ai(
                product_name=prod.product_name,
                product_description=prod.product_description,
                product_category=prod.product_category,
                product_features=prod.product_features,
                price=prod.price,
                tags=prod.tags,
                brand_name=brand.brand_name,
                brand_voice=brand.voice,
                brand_tone=brand.tone,
                campaign_goal=goal.value,
                message_angle=angles[0].value,
                template_name=static_ad_templates[0].template_name if static_ad_templates else "Hero Product",
                trending_keywords=market.trending_keywords,
                target_age_min=market.target_audience_age_min,
                target_age_max=market.target_audience_age_max,
                target_gender=market.target_audience_gender,
                num_variants=static_variant_count,
            )

        static_ad_variants: List[StaticAdVariantPlan] = []
        for vi in range(static_variant_count):
            angle = angles[vi % len(angles)]
            # Cycle through templates if we have more variants than templates
            sa_template = static_ad_templates[vi % len(static_ad_templates)] if static_ad_templates else None
            tpl_category = sa_template.category if sa_template else "hero_product_showcase"

            # Use AI static copy if available, else smart deterministic
            if ai_static_copies and vi < len(ai_static_copies):
                sa_copy = ai_static_copies[vi]
                headline = sa_copy.headline
                subheading = sa_copy.subheading
                cta = sa_copy.cta_text
                body_text = sa_copy.body_text
            else:
                sa_copy = generate_static_ad_copy_deterministic(
                    product_name=prod.product_name,
                    product_description=prod.product_description,
                    product_category=prod.product_category,
                    product_features=prod.product_features,
                    price=prod.price,
                    tags=prod.tags,
                    brand_name=brand.brand_name,
                    campaign_goal=goal.value,
                    message_angle=angle.value,
                    template_category=tpl_category,
                    trending_keywords=market.trending_keywords,
                    target_age_min=market.target_audience_age_min,
                    target_age_max=market.target_audience_age_max,
                    target_gender=market.target_audience_gender,
                    variant_idx=vi,
                )
                headline = sa_copy.headline
                subheading = sa_copy.subheading
                cta = sa_copy.cta_text
                body_text = sa_copy.body_text

            selected_image = image_pool[vi % len(image_pool)] if image_pool else ""
            image_url = ""
            if selected_image:
                if image_override:
                    image_url = selected_image
                else:
                    primary = getattr(prod, "product_image_url", "")
                    if not primary or selected_image != primary:
                        image_url = selected_image

            static_ad_variants.append(StaticAdVariantPlan(
                variant_id=vi + 1,
                variant_type=VARIANT_TYPES[vi % len(VARIANT_TYPES)].value,
                message_angle=angle.value,
                headline=headline,
                subheading=subheading,
                cta_text=cta,
                body_text=body_text,
                static_template_id=sa_template.template_id if sa_template else "",
                static_template_name=sa_template.template_name if sa_template else "",
                image_url=image_url,
            ))

        product_plans.append(ProductCreativePlan(
            product_index=idx,
            product_name=prod.product_name,
            video_style=video_style.value,
            visual_style=visual_style.value,
            variants=variants,
            static_ad_variants=static_ad_variants,
        ))

    # 5. General brand plan
    product_names = [p.product_name for p in products]
    brand_variants_list: List[VideoVariantPlan] = []
    brand_template_ids: List[str] = []
    if db is not None:
        brand_templates = await select_templates(
            db,
            visual_style=visual_style,
            video_style=VideoStyle.PRODUCT_HERO,
            duration=duration,
            aspect_ratios=aspect_ratios,
            industry=brand.industry,
            limit=brand_variants,
        )
        brand_template_ids = [str(t.id) for t in brand_templates]

    for vi in range(brand_variants):
        angle = angles[vi % len(angles)]

        # Try AI copy first, fall back to templates
        if ai_brand_copies is not None and vi < len(ai_brand_copies):
            ai_b = ai_brand_copies[vi]
            primary = ai_b.primary_message
            secondary = ai_b.secondary_message
            cta = ai_b.cta_text
        else:
            primary = resolve_brand_primary_message(angle, vi)
            secondary = resolve_secondary_message(market.sentiment)
            cta = resolve_cta(goal, is_brand=True, variant_idx=vi)

        brand_variants_list.append(VideoVariantPlan(
            variant_id=vi + 1,
            variant_type=VARIANT_TYPES[vi % len(VARIANT_TYPES)].value,
            message_angle=angle.value,
            primary_message=primary,
            secondary_message=secondary,
            cta_text=cta,
            template_id=brand_template_ids[vi] if vi < len(brand_template_ids) else None,
            pacing=pacing_label,
            pacing_seconds=pacing_secs,
        ))

    layout_types = [
        resolve_layout_type(len(products), vi).value for vi in range(brand_variants)
    ]

    # Select static ad templates for brand-level ads (full context)
    # Generate more brand static ads for collection/collaboration showcases
    brand_static_count = max(brand_variants * 2, 8)  # At least 8 brand/collection ads
    brand_static_templates = select_brand_static_templates(
        goal=goal,
        message_angles=[angles[vi % len(angles)] for vi in range(brand_static_count)],
        industry=brand.industry,
        visual_style=visual_style.value,
        product_count=len(products),
        count=brand_static_count,
        sentiment=market.sentiment.value,
        target_age_min=market.target_audience_age_min,
        target_age_max=market.target_audience_age_max,
        trending_keywords=market.trending_keywords,
    )

    from app.services.static_ad.copywriter import generate_brand_static_ad_copy_deterministic

    brand_static_ad_variants: List[StaticAdVariantPlan] = []
    for vi in range(brand_static_count):
        angle = angles[vi % len(angles)]
        # Cycle through templates if needed
        sa_tpl = brand_static_templates[vi % len(brand_static_templates)] if brand_static_templates else None
        tpl_category = sa_tpl.category if sa_tpl else "benefit_grid_triple"

        # Use AI brand copy if available, else smart deterministic
        if ai_brand_copies is not None and vi < len(ai_brand_copies):
            ai_b = ai_brand_copies[vi]
            headline = ai_b.primary_message
            subheading = ai_b.secondary_message
            cta = ai_b.cta_text
            body_text = ", ".join(product_names[:5])
        else:
            sa_copy = generate_brand_static_ad_copy_deterministic(
                brand_name=brand.brand_name,
                brand_industry=brand.industry,
                product_names=product_names,
                campaign_goal=goal.value,
                message_angle=angle.value,
                template_category=tpl_category,
                trending_keywords=market.trending_keywords,
                target_age_min=market.target_audience_age_min,
                target_age_max=market.target_audience_age_max,
                variant_idx=vi,
            )
            headline = sa_copy.headline
            subheading = sa_copy.subheading
            cta = sa_copy.cta_text
            body_text = sa_copy.body_text

        brand_static_ad_variants.append(StaticAdVariantPlan(
            variant_id=vi + 1,
            variant_type=VARIANT_TYPES[vi % len(VARIANT_TYPES)].value,
            message_angle=angle.value,
            headline=headline,
            subheading=subheading,
            cta_text=cta,
            body_text=body_text,
            static_template_id=sa_tpl.template_id if sa_tpl else "",
            static_template_name=sa_tpl.template_name if sa_tpl else "",
        ))

    brand_plan = GeneralBrandPlan(
        layout_types=layout_types,
        products_shown=product_names,
        visual_style=visual_style.value,
        variants=brand_variants_list,
        static_ad_variants=brand_static_ad_variants,
    )

    total_videos = len(products) * product_variants + brand_variants
    total_static_ads = sum(len(p.static_ad_variants) for p in product_plans) + len(brand_static_ad_variants)

    return CampaignStrategy(
        visual_style=visual_style.value,
        pacing=pacing_label,
        pacing_seconds=pacing_secs,
        message_angles=[a.value for a in angles],
        product_plans=product_plans,
        brand_plan=brand_plan,
        platforms=[p.value for p in platforms],
        total_videos=total_videos,
        total_static_ads=total_static_ads,
    )
